name: fortunetelling-release

on:
  push:
    branches: ["main"]
    tags:
      # See https://semver.org/ for Semantic Versioning
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  # Status check job
  use-status-check:
    # adapt to point to the current repo
    # https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#calling-a-reusable-workflow
    uses: cse110-sp23-group15/cse110-sp23-group15/.github/workflows/fortunetelling-status-check.yml@main

  # Release Job
  release:
    name: fortunetelling-release
    runs-on: ubuntu-latest
    needs: use-status-check
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Generate CHANGELOG via conventionalcommits https://www.conventionalcommits.org/en/v1.0.0/
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      # Create new release
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}

      # Update and commit CHANGELOG.md. Skip CI workflows
      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'docs: update fortunetelling CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md
          # Push to protected branches https://github.com/stefanzweifel/git-auto-commit-action#action-does-not-push-commit-to-repository-authentication-issue
          # This is necessary since we are an organization. Alternative is to create PAT but its too much work
          # Must allow force push in main
          push_options: --force
